Add "Clear" button to logs
LycheeOrg/Lychee pull request #1374
Opened 2022-06-16 06:55 UTC by qwerty287

https://github.com/LycheeOrg/Lychee-front/pull/302

2022-06-16 07:02 UTC, qwerty287 commented
CI failure is unrelated.

2022-06-16 19:12 UTC, kamil4 requested changes

2022-06-16 19:12 UTC, kamil4 commented on app/Locale/Dutch.php
> +			'CLEAR' => 'Leeren',
My Dutch is a little rusty but I don't believe that's the right word, and the official Dutch dictionary seems to agree (https://www.vandale.nl/gratis-woordenboek/nederlands/betekenis/leeren).

2022-06-17 05:47 UTC, qwerty287 commented on app/Locale/Dutch.php
> +			'CLEAR' => 'Leeren',
Whoops looks like I changed Dutch instead of German ;) ("German" in German is "Deutsch", so I probably misread the filename)

2022-07-20 06:54 UTC, ildyria approved these changes
LGTM. fix conflict & can merge.

2022-07-20 07:35 UTC, qwerty287 commented
@kamil4 you have to approve because you requested changes and I don't want to use the force-merge option as admin :)

2022-07-20 16:56 UTC, kamil4 approved these changes

2022-07-20 16:59 UTC, merged