Shared albums should not consider the `require_link` property.
LycheeOrg/Lychee pull request #1480
Opened 2022-08-23 10:01 UTC by ildyria

Fixes #1478 

```php
/**
 *  - the user is the admin, or
 *  - the user is the owner, or
 *  - the album does not require a direct link and is shared with the user, or
 *  - the album does not require a direct link, is public and has no password set, or
 *  - the album does not require a direct link, is public and has been unlocked
 */
```

After further thoughts, this is pretty counter intuitive. We should have fixed that one a long time ago. :)

2022-08-23 10:02 UTC, ildyria commented
I am not sure if I missed some other conditions.

2022-08-23 17:11 UTC, nagmat84 requested changes
You missed the conditions in line 82 and 360.

Moreover, I am in strong favor of tests which checks the new behavior. At the moment, we seem to have reached a point which is rather bug-free with respect to security issues (i.e. accidentally leaking a photo which should stay hidden). Any change in the SQL queries might break that and hence, tests would be wonderful.

Or we could just wait until https://github.com/LycheeOrg/Lychee/issues/1462 is ready. As I detailed out in https://github.com/LycheeOrg/Lychee/issues/1478 there might actually be other users who rely on exactly this feature, i.e. that albums can also be hidden from users with whom they are shared. (Although, I lack the imagination of a meaningful use-case for that.)

I am still wondering if we should make "hidden" a per-share option. @kamil4 raised the same question in https://github.com/LycheeOrg/Lychee/pull/1357#issuecomment-1215763003, 3rd bullet point. This being said, I am not sure, if we should change the behavior now or simply wait until https://github.com/LycheeOrg/Lychee/issues/1462. At least, the implementation works as designed and intended.

2022-08-23 17:11 UTC, nagmat84 commented on app/Policies/AlbumQueryPolicy.php
> +	 *  - the album is shared with the user
You have changed the comment of the method, but not the method itself, see lines 81-83 below. How so?

Maybe we should also have some tests which checks the new behavior.

2022-08-23 21:17 UTC, ildyria commented on app/Policies/AlbumQueryPolicy.php
> +	 *  - the album is shared with the user
yeah I was thinking about adding some tests in that regard. At least to reproduce the bug and then kill it :)

2022-09-06 14:41 UTC, ildyria commented
As per requested, added tests. :)

2022-09-07 10:18 UTC, ildyria commented
IDK what happened O.o but this is definitively not something I wanted o close. :'D

2022-09-11 14:33 UTC, nagmat84 approved these changes
LGTM, but untested. I only checked all the boolean conditions in the query (which was difficult enough :laughing:) and could not spot any remaining error.

@ildyria I assume you have tested it yourself and found no regression?

2022-09-11 19:32 UTC, ildyria commented
> @ildyria I assume you have tested it yourself and found no regression?

Yes.

2022-09-11 19:32 UTC, ildyria commented
Also the tests you added are making it pretty tight to create regressions :)

2022-09-11 19:43 UTC, merged