Add option to skip diagnostic checks
LycheeOrg/Lychee pull request #1558
Opened 2022-10-17 15:50 UTC by qwerty287

Closes https://github.com/LycheeOrg/Lychee/issues/1555

1. Allows to add a new env var with class names of checks that will be skipped.
2. Allows to define as many `--skip` options you want containing class names of checks (e.g. `TimezoneCheck`) and skip the check then. May be helpful if you have checks that would take a long time to run (just as described in #1555)

2022-10-18 08:51 UTC, ildyria commented
One one hand, I would say LGTM.
On the other hand I would say that the permission check should be skipped in the case of S3.

2022-10-18 11:13 UTC, d7415 commented
> On the other hand I would say that the permission check should be skipped in the case of S3.

The way that works at the moment (mounting S3 as a local filesystem), we have no way of knowing.

2022-10-18 19:43 UTC, kamil4 commented
Ideally there should also be a way to skip the tests for the Diagnostics initiated by the frontend. So maybe this should be a config option that works for both the frontend and the commandline and the `--skip` could then override it?

2022-10-19 06:59 UTC, qwerty287 commented
@kamil4 I implemented this option in https://github.com/LycheeOrg/Lychee/pull/1558/commits/ef390b5b5cf1d99b973e9b2f51d465c9b9854469.

2022-10-19 13:15 UTC, ildyria approved these changes
LGTM.

I thought you meant a DB config, but indeed in the `.env` it makes more sense.

2022-10-19 13:17 UTC, ildyria requested changes
Please add `#SKIP_DIAGNOSTICS_CHECKS=` and short description in `.env.example` :)

2022-10-19 13:17 UTC, ildyria commented on config/app.php
> +	'skip_diagnostics_checks' => explode(',', env('SKIP_DIAGNOSTICS_CHECKS', '')),
Please add `#SKIP_DIAGNOSTICS_CHECKS=` and short description in `.env.example` :)

2022-10-19 14:05 UTC, kamil4 approved these changes
LGTM (untested). Indeed I did mean a config in the DB, but one in `.env` probably makes more sense (and I agree with @ildyria that there should be an example).

2022-10-19 14:39 UTC, ildyria approved these changes
LGTM.

2022-10-19 16:48 UTC, merged