Smart album - On This Day - new feature
LycheeOrg/Lychee pull request #1607
Opened 2022-11-27 14:47 UTC by aldjordje

The smart album "On This Day" will allow users to see all the photos taken on this day.

2022-11-27 16:09 UTC, ildyria commented on app/Locale/French.php
> +			'ON_THIS_DAY' => 'On This Day',
```suggestion
			'ON_THIS_DAY' => 'Ce jour-là',
```

2022-11-27 16:16 UTC, ildyria commented
@aldjordje I sent you an Triage invite so you are able to run the pipelines without waiting for our approval. :)

2022-11-27 16:18 UTC, ildyria commented on app/Locale/Dutch.php
> +			'ON_THIS_DAY' => 'On This Day',
```suggestion
			'ON_THIS_DAY' => 'Deze Dag',
```
(from my basic knowledge of Dutch :') )
@nagmat84 should be able to give you the one in German

2022-11-27 17:06 UTC, qwerty287 commented on app/Locale/German.php
> +			'ON_THIS_DAY' => 'On This Day',
```suggestion
			'ON_THIS_DAY' => 'An diesem Tag',
```

2022-11-27 18:30 UTC, qwerty287 commented on app/SmartAlbums/OnThisDayAlbum.php
> +					'extract(month from photos.taken_at) = ? and extract(day from photos.taken_at) = ?',
Is it intentional to not use check the year here?

2022-11-27 18:46 UTC, aldjordje commented on app/SmartAlbums/OnThisDayAlbum.php
> +					'extract(month from photos.taken_at) = ? and extract(day from photos.taken_at) = ?',
Yes, this will return all the photos taken on this day from every year.

2022-12-05 18:43 UTC, ildyria commented
@aldjordje is this ready for review ? :)

2022-12-06 10:13 UTC, aldjordje commented
@ildyria Thank you for enabling exceptions for 500 errors to be displayed. Without it, I couldn't figure out what the problem was :)

2022-12-06 10:19 UTC, ildyria requested changes
99% LGTM.

Please add the following standalone test to `AlbumTest.php`.

1. Get today date
2. Log as admin
3. Upload photo -> get the photo ID
4. Get photo model and set taken_at of the picture to today - 1 year.
5. Open "On this day"
6. Check that photo ID is present in the response.
7. Log out.

This will guarantee that the SQL request is also working. :)

Some pictures do not have a `taken_at` (exif data missing), maybe in those case we could consider the `created_at` instead ? See https://github.com/aldjordje/Lychee/pull/1/files :)

2022-12-06 10:35 UTC, aldjordje commented
@ildyria I was thinking about the test and I couldn't  think of a way to write it. I'll add it today.

2022-12-06 18:01 UTC, ildyria approved these changes
LGTM.

2022-12-06 18:15 UTC, merged