:warning:  Add Caching for faster response time.
LycheeOrg/Lychee pull request #2859
Opened 2024-12-28 23:10 UTC by ildyria

Currently broken.

2025-01-10 10:40 UTC, ildyria commented on resources/js/components/maintenance/MaintenanceFlushCache.vue
> +				{{ "Flush Cache" }}
Need to be localized ;)

2025-01-15 14:32 UTC, tinohager commented
@d7415 Hello Martin, I would be delighted if you could take a look here :)

2025-01-16 21:39 UTC, ildyria commented on resources/js/components/maintenance/MaintenanceFlushCache.vue
> +				{{ "Flush Cache" }}
Fixed.

2025-01-31 09:03 UTC, tinohager commented
@ildyria Will we make any progress here in the near future?

2025-01-31 15:48 UTC, ildyria commented
> @ildyria Will we make any progress here in the near future?

I hope so. :)

If @RonnieTaz  or @JasonMillward  or @sancsin  have some time to take a look.

2025-02-01 16:50 UTC, sancsin commented
I can have a look at it a little today. Can't promise that I will be able to go through everything today though. But will try my best

2025-02-02 19:12 UTC, sancsin requested changes

2025-02-02 19:12 UTC, sancsin commented on app/Actions/Photo/Create.php
> +				/** @disregard */
What is this comment for? Doesn't seem to be standard PHPDoc comment?

2025-02-02 19:12 UTC, sancsin commented on app/Http/Controllers/ProfileController.php
> +		TaggedRouteCacheUpdated::dispatch(CacheTag::USER);
Should we havve this line before `Auth::login($currentUser);` in-case it throws an error?

2025-02-02 19:12 UTC, sancsin commented on app/Http/Controllers/ProfileController.php
> +		TaggedRouteCacheUpdated::dispatch(CacheTag::USER);
Should we have this after `do` call?

2025-02-02 19:12 UTC, sancsin commented on app/Listeners/AlbumCacheCleaner.php
> +		$routes = $this->route_cache_manager->retrieve_routes_for_tag(CacheTag::GALLERY, with_extra: false, without_extra: true);
shouldn't `without_extra:false` imply  `with_extra: true`, without needing extra variable for `without_extra`. Why do we need this?

2025-02-02 19:12 UTC, sancsin commented on app/Metadata/Cache/RouteCacheManager.php
> +			'api/v2/Diagnostics::config' => false,
What about these? Will these need to be cached later or they will never be?

2025-02-02 19:12 UTC, sancsin commented on app/Metadata/Cache/RouteCacheManager.php
> +			'api/v2/Search::init' => false,
No, need to cache this either or? Shall we add a comment here?

2025-02-02 19:12 UTC, sancsin commented on app/Metadata/Cache/RouteCacheManager.php
> +			'api/v2/WebAuthn' => false,
No, need to cache this either or? Shall we add a comment here?

2025-02-02 22:35 UTC, ildyria commented on app/Actions/Photo/Create.php
> +				/** @disregard */
This is because VS Code is complaining about some method not found on the DTO:
![image](https://github.com/user-attachments/assets/e8f0c23b-4da5-4c35-942b-e39352ea5ea1)

2025-02-02 22:37 UTC, ildyria commented on app/Listeners/AlbumCacheCleaner.php
> +		$routes = $this->route_cache_manager->retrieve_routes_for_tag(CacheTag::GALLERY, with_extra: false, without_extra: true);
The thing is you need to be able to filter:
- without the extra part only.
- with the extra part only.
- all of them.

One single boolean does not accomplish this.
I am open to other ideas of how to implement this filtering.

2025-02-02 22:38 UTC, ildyria commented on app/Metadata/Cache/RouteCacheManager.php
> +			'api/v2/Diagnostics::config' => false,
We do not want to cache diagnostics as they are a debugging tool. The MUST represent the state of Lychee at any time.

2025-02-02 22:52 UTC, ildyria commented on app/Http/Controllers/ProfileController.php
> +		TaggedRouteCacheUpdated::dispatch(CacheTag::USER);
WRTC: [c2da654](https://github.com/LycheeOrg/Lychee/pull/2859/commits/c2da654f5a8d69b7165ca8c6564b4abc04f0371d)

but not really necessary.

2025-02-02 22:52 UTC, ildyria commented on app/Http/Controllers/ProfileController.php
> +		TaggedRouteCacheUpdated::dispatch(CacheTag::USER);
Good catch. [c2da654](https://github.com/LycheeOrg/Lychee/pull/2859/commits/c2da654f5a8d69b7165ca8c6564b4abc04f0371d).

2025-02-02 22:53 UTC, ildyria commented on app/Metadata/Cache/RouteCacheManager.php
> +			'api/v2/Diagnostics::config' => false,
clarified: [7a5ab8f](https://github.com/LycheeOrg/Lychee/pull/2859/commits/7a5ab8f69b912cc3b26684f42e4430bb1c3099f9)

2025-02-02 22:53 UTC, ildyria commented on app/Metadata/Cache/RouteCacheManager.php
> +			'api/v2/Search::init' => false,
clarified: [7a5ab8f](https://github.com/LycheeOrg/Lychee/pull/2859/commits/7a5ab8f69b912cc3b26684f42e4430bb1c3099f9)

2025-02-02 22:53 UTC, ildyria commented on app/Metadata/Cache/RouteCacheManager.php
> +			'api/v2/WebAuthn' => false,
fixed [7a5ab8f](https://github.com/LycheeOrg/Lychee/pull/2859/commits/7a5ab8f69b912cc3b26684f42e4430bb1c3099f9)

And added clear cache on WebAuthn operations: [3f45d6e](https://github.com/LycheeOrg/Lychee/pull/2859/commits/3f45d6e7ec76b1c3557cd5e53a19571952ba938e)

2025-02-03 07:34 UTC, sancsin commented on app/Listeners/AlbumCacheCleaner.php
> +		$routes = $this->route_cache_manager->retrieve_routes_for_tag(CacheTag::GALLERY, with_extra: false, without_extra: true);
Maybe we can use enums with bitwise & and | operations to check the different combinations and take actions based on that?

2025-02-03 11:26 UTC, ildyria commented on app/Listeners/AlbumCacheCleaner.php
> +		$routes = $this->route_cache_manager->retrieve_routes_for_tag(CacheTag::GALLERY, with_extra: false, without_extra: true);
Fixed: [a6464a3](https://github.com/LycheeOrg/Lychee/pull/2859/commits/a6464a38cb6220c38813988b1443d25004bd414d) :)

2025-02-03 11:51 UTC, sancsin requested changes

2025-02-03 11:51 UTC, sancsin commented on app/Metadata/Cache/RouteCacheManager.php
> +				// Or with extra is set to true and we have extra parameters => ignore condition
```suggestion
				// Either with ONLY_WITH_EXTRA flag not set => ignore condition
				// Or with ONLY_WITH_EXTRA flag set and we have extra parameters => ignore condition
```

2025-02-03 11:53 UTC, sancsin approved these changes

2025-02-03 15:43 UTC, merged