add Traditional Chinese
LycheeOrg/Lychee pull request #667
Opened 2020-07-20 09:50 UTC by ildyria

fixes #661 

Thank you @Oliverlin67 for your good work, we are just short of the 3 following translations:

```php
			'MIGRATION_AVAILABLE' => 'Migration available!',
```

```php
			'PHOTO_EDIT_ROTATECWISE' => 'Rotate clockwise',
			'PHOTO_EDIT_ROTATECCWISE' => 'Rotate counter-clockwise',
```

2020-07-20 13:15 UTC, Oliverlin67 commented
`'MIGRATION_AVAILABLE' => '可進行轉移!',`

`'PHOTO_EDIT_ROTATECWISE' => '順時針旋轉',
 'PHOTO_EDIT_ROTATECCWISE' => '逆時針旋轉',`

2020-07-20 13:19 UTC, Oliverlin67 requested changes

2020-07-20 13:19 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'PHOTO_EDIT_ROTATECCWISE' => 'Rotate counter-clockwise',
'PHOTO_EDIT_ROTATECCWISE' => '逆時針旋轉',

2020-07-20 13:20 UTC, Oliverlin67 requested changes

2020-07-20 13:20 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'PHOTO_EDIT_ROTATECWISE' => 'Rotate clockwise',
'PHOTO_EDIT_ROTATECWISE' => '順時針旋轉',

2020-07-20 13:20 UTC, ildyria commented on app/Locale/ChineseTraditional.php
> +			'PHOTO_EDIT_ROTATECWISE' => 'Rotate clockwise',
already fixed. :'D

2020-07-20 13:20 UTC, ildyria commented on app/Locale/ChineseTraditional.php
> +			'PHOTO_EDIT_ROTATECCWISE' => 'Rotate counter-clockwise',
already fixed. :'D

2020-07-20 13:21 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'MIGRATION_AVAILABLE' => 'Migration available!',
'MIGRATION_AVAILABLE' => '可進行轉移!',

2020-07-20 13:21 UTC, ildyria commented on app/Locale/ChineseTraditional.php
> +			'MIGRATION_AVAILABLE' => 'Migration available!',
already fixed. :'D

2020-07-20 13:22 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'PHOTO_EDIT_ROTATECWISE' => 'Rotate clockwise',
> 已經修復。：'D

WOW high efficiency! @~@

2020-07-20 13:23 UTC, ildyria commented on app/Locale/ChineseTraditional.php
> +			'PHOTO_EDIT_ROTATECWISE' => 'Rotate clockwise',
I get mails whenever there is something happening to this repository. :smile:

2020-07-20 13:37 UTC, Oliverlin67 requested changes

2020-07-20 13:37 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'MIGRATION_AVAILABLE' => 'Migration available!',
'MIGRATION_AVAILABLE' => '可以遷移!',

2020-07-20 13:51 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'HOSTED_WITH_LYCHEE' => 'Hosted with Lychee',
'HOSTED_WITH_LYCHEE' => '使用Lychee託管照片',

2020-07-20 13:52 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'UPLOAD_IMPORT_UNSUPPORTED' => '不支持的文件類型！',
'UPLOAD_IMPORT_UNSUPPORTED' => '不支援的文件類型！',

2020-07-20 13:53 UTC, ildyria commented on app/Locale/ChineseTraditional.php
> +			'UPLOAD_IMPORT_UNSUPPORTED' => '不支持的文件類型！',
I don't see the difference. :thinking:

2020-07-20 14:06 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'DELETE_ALBUMS_QUESTION' => '删刪除相簿和照片',
'DELETE_ALBUMS_QUESTION' => '刪除相簿和照片',

2020-07-20 14:07 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'ALBUM_SHARING' => '共享',
'ALBUM_SHARING' => '分享',

2020-07-20 14:07 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'ALBUM_FULL_EXPL' => '提供全分辨率圖片。',
'ALBUM_FULL_EXPL' => '提供完整解析度照片',

2020-07-20 14:08 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'ALBUM_HIDDEN_EXPL' => '只有使用外部連結才能查看。',
'ALBUM_HIDDEN_EXPL' => '只有知道連結者才能檢視',

2020-07-20 14:08 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'ALBUM_DOWNLOADABLE_EXPL' => '訪客可己下載該相簿',
'ALBUM_DOWNLOADABLE_EXPL' => '訪客可以下載該相簿',

2020-07-20 14:09 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'PHOTO_DELETE_2' => '？此動作無法還原！',
'PHOTO_DELETE_2' => '此動作無法還原！',

2020-07-20 14:09 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'PHOTO_MAKE_PRIVATE_ALBUM' => '此照片位於公開相簿中。編輯所在相冊的隱私設定，將其設置為公開或私有。',
'PHOTO_MAKE_PRIVATE_ALBUM' => '此照片位於公開相簿中。編輯所在相簿的隱私設定，將其設置為公開或私有。',

2020-07-20 14:09 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'PHOTO_SHARE_BUTTON_VISIBLE' => '分享按鈕可用',
'PHOTO_SHARE_BUTTON_VISIBLE' => '顯示分享按鈕',

2020-07-20 14:10 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'SETTINGS_SUCCESS_LOGIN' => '登錄信息已更新',
'SETTINGS_SUCCESS_LOGIN' => '登入資訊已更新',

2020-07-20 14:11 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'EDIT_SHARING_TEXT' => '相冊的共享屬性將被修改為：',
'EDIT_SHARING_TEXT' => '相簿的共享屬性將被修改為：',

2020-07-20 14:11 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'SHARE_ALBUM_TEXT' => '該相冊的共享屬性：',
'SHARE_ALBUM_TEXT' => '該相簿的共享屬性：',

2020-07-20 14:11 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'SORT_ALBUM_SELECT_4' => '公开',
```suggestion
			'SORT_ALBUM_SELECT_4' => '公開',
```

2020-07-20 14:12 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'UPLOAD_FAILED_ERROR' => '上傳失敗。服務器傳回了一個錯誤！',
'UPLOAD_FAILED_ERROR' => '上傳失敗。伺服器傳回了一個錯誤！',

2020-07-20 14:12 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'UPLOAD_FAILED_WARNING' => '上傳失敗。服務器傳回了一個警告！',
'UPLOAD_FAILED_WARNING' => '上傳失敗。伺服器傳回了一個警告！',

2020-07-20 14:12 UTC, ildyria commented
@Oliverlin67 when you do a comment, you can actually suggest directly changes.
See below:
![2020-07-20_1920x1080_16:12:09](https://user-images.githubusercontent.com/627094/87947596-daf21680-caa3-11ea-9bc4-6e73c765e201.png)

2020-07-20 14:12 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'UPLOAD_UNKNOWN' => '服務器返回未知響應。請查看瀏覽器控制台獲取詳細信息。',
'UPLOAD_UNKNOWN' => '伺服器傳回了未知響應。請查看瀏覽器控制台獲取詳細信息。',

2020-07-20 14:13 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'UPLOAD_ERROR_UNKNOWN' => '上傳失敗。服務器回傳了一個未知錯誤！',
'UPLOAD_ERROR_UNKNOWN' => '上傳失敗。伺服器回傳了一個未知錯誤！',

2020-07-20 14:13 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'UPLOAD_IMPORT_SERVER' => '從服務器導入',
'UPLOAD_IMPORT_SERVER' => '從伺服器導入',

2020-07-20 14:14 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'UPLOAD_IMPORT_LOW_MEMORY_EXPL' => '服務器上的導入過程已接近內存限制，並可能最終被提前終止。',
'UPLOAD_IMPORT_LOW_MEMORY_EXPL' => '伺服器上的導入過程已接近內存限制，並可能最終被提前終止。',

2020-07-20 14:14 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'HOSTED_WITH_LYCHEE' => 'Hosted with Lychee',
'HOSTED_WITH_LYCHEE' => '使用Lychee託管照片',

2020-07-20 14:15 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'DELETE_ALBUMS_CONFIRMATION_2' => '選取的相冊和其中的所有照片？此動作無法還原！',
'DELETE_ALBUMS_CONFIRMATION_2' => '選取的相簿和其中的所有照片？此動作無法還原！',

2020-07-20 14:15 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'TAGS_ALL' => '大量標籤',
'TAGS_ALL' => '批量標籤',

2020-07-20 14:16 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'ALBUM_PUBLIC_EXPL' => '相簿可以被其他人查看，但要遵守以下限制。',
```suggestion
			'ALBUM_PUBLIC_EXPL' => '相簿可以被其他人查看，但需遵守以下限制 : ',
```

2020-07-20 14:17 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'ALBUM_FULL' => '原版',
'ALBUM_FULL' => '原圖',

2020-07-20 14:17 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'ALBUM_SHARE_BUTTON_VISIBLE' => '分享按鈕是可見的',
'ALBUM_SHARE_BUTTON_VISIBLE' => '顯示分享按鈕',

2020-07-20 14:18 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'PHOTO_FULL' => '原始',
'PHOTO_FULL' => '原圖',

2020-07-20 14:19 UTC, Oliverlin67 commented on app/Locale/ChineseTraditional.php
> +			'ERROR_UNKNOWN' => '發生未知問題！請再試一次，檢查您的安裝和服務器。請查看自述文件以獲取更多信息。',
'ERROR_UNKNOWN' => '發生未知問題！請再試一次，檢查您的安裝和伺服器。請查看自述文件以獲取更多信息。',

2020-07-20 14:22 UTC, Oliverlin67 commented
> @Oliverlin67 when you do a comment, you can actually suggest directly changes.
> See below:
> ![2020-07-20_1920x1080_16:12:09](https://user-images.githubusercontent.com/627094/87947596-daf21680-caa3-11ea-9bc4-6e73c765e201.png)

Sorry (@~@)

2020-07-20 14:24 UTC, ildyria commented
> Sorry (@~@)

I already edited some of your comments to make them easier to integrate. :)

2020-07-20 14:25 UTC, Oliverlin67 commented
@ildyria Everything I found changed :D

2020-07-20 15:01 UTC, ildyria commented
@Oliverlin67 can you double check again ?

2020-07-24 08:09 UTC, merged

2020-07-26 07:42 UTC, Oliverlin67 commented
@ildyria No translation errors~