Feature/#48 album by tags
LycheeOrg/Lychee pull request #704
Opened 2020-08-27 17:41 UTC by Aleshus

Added support for tag albums

2020-08-27 21:50 UTC, ildyria commented
@Aleshus thank you for your PR. Can you do `make formatting` at the base of the repository so that it unifies the style. :+1:

2020-08-28 06:22 UTC, Aleshus commented
> @Aleshus thank you for your PR. Can you do `make formatting` at the base of the repository so that it unifies the style. 👍

Ok a ran it and it changed 229 files - line endings from CRLF to LF. Is it ok?

2020-09-01 10:10 UTC, ildyria reviewed
Please double check my changes. :)

2020-09-01 10:10 UTC, ildyria commented on app/ModelFunctions/AlbumsFunctions.php
> +		$albumIDs = new BaseCollection();
nicely spotted.

2020-09-01 10:13 UTC, ildyria commented on app/ModelFunctions/AlbumFunctions.php
> +	public static function is_tag_album(Album $album): bool
Not sure if this needs to be static anymore.

2020-09-02 03:45 UTC, kamil4 requested changes
Github's change line count made me apprehensive about reviewing this; thankfully, most of it was the front end and the languages...

2020-09-02 03:45 UTC, kamil4 commented on app/Http/Controllers/AlbumController.php
> +		$album->id = Helpers::generateID();
You don't need these two lines. `AlbumFunctions.createTagAlbum` takes care of that.

2020-09-02 03:45 UTC, kamil4 commented on app/Http/Controllers/AlbumController.php
> +		// TODO: improve here.
@ildyria Cryptic as always :wink:.

2020-09-02 03:45 UTC, kamil4 commented on app/Http/Controllers/AlbumController.php
> +			'show_tags' => 'string|required|max:1000|min:1',
Is there a reason to have a max? While `1000` seems like a lot, I wonder if an arbitrary limit is necessary at all?

2020-09-02 03:45 UTC, kamil4 commented on app/ModelFunctions/AlbumFunctions.php
> +	 * @param array  $tags
Change of plans here? I don't see that argument being added to the actual function below...

2020-09-02 03:45 UTC, kamil4 commented on app/SmartAlbums/TagAlbum.php
> +		// /!\ this may reveal private picture.
@ildyria Are you sure? I don't see the code doing anything different from Starred or Recent. In particular, `filter` is being applied at the end. We should test, of course...

2020-09-05 06:00 UTC, kamil4 approved these changes
I pushed additional commits that:
* revert the `is_smart_album` changes. We need it to trigger only for the base smart albums in the upload check middleware; otherwise everybody could modify/delete the tagged smart albums.
* refactor album download code. It didn't work for tagged smart album and was using obsolete functionality for other albums anyway so it was due for an overhaul.
* I verified that @ildyria's concern about `TagAlbum\get_photos` leaking private pictures was unfounded.

This should be good to go now!

2020-09-07 08:25 UTC, merged