more refactoring
LycheeOrg/Lychee pull request #873
Opened 2021-01-15 21:45 UTC by ildyria

Just a few more stuff.

2021-01-17 05:24 UTC, kamil4 requested changes
I reviewed it unasked since I want to make changes to some of this functionality (Import, Rotate) and I'd rather do it to the refactored versions :smiley:.

I spotted one regression: importing folders with subdirectories fails again.

Also, there's a suspicious-looking query in the RSS code but that was there before as well...

2021-01-17 05:24 UTC, kamil4 commented on app/Actions/Import/Exec.php
> +		// star als wildcard (as in *.jpg)
Typo: `als` -> `as`

2021-01-17 05:24 UTC, kamil4 commented on app/Actions/Import/Exec.php
> +			$raw_formats = strtolower(Configs::get_value('raw_formats', ''));
I don't think this needs to be looked up in every new iteration?

2021-01-17 05:24 UTC, kamil4 commented on app/Actions/Import/FromServer.php
> +			$this->exec->delete_imported = $validated['delete_imported'] === '1';
Add parentheses? (also two lines below)

2021-01-17 05:24 UTC, kamil4 commented on app/Actions/RSS/Generate.php
> +			->where(fn ($q) => $q->whereIn('album_id', $publicIds)->orWhere('public', '=', '1'))
What's the reason behind this additional `orWhere`? Won't it expose the content of hidden or password-protected albums?

2021-01-17 05:24 UTC, kamil4 commented on app/Actions/Import/Exec.php
> +				$create = resolve(AlbumCreate::class);
This fails; `use` missing (and now that the use of `Photo\Create` is in another file, I guess it no longer needs to be renamed to `AlbumCreate`?).

2021-01-17 05:24 UTC, kamil4 commented on app/Actions/Photo/Rotate.php
> +			Logs::error(__METHOD__, __LINE__, 'Synlinked images cannot be rotated');
Typo; `Synlinked` -> `Symlinked`

2021-01-18 10:20 UTC, ildyria commented on app/Actions/Import/Exec.php
> +		// star als wildcard (as in *.jpg)
https://translate.google.nl/?sl=nl&tl=en&text=als&op=translate :nerd_face:

2021-01-18 10:21 UTC, ildyria commented on app/Actions/Import/Exec.php
> +			$raw_formats = strtolower(Configs::get_value('raw_formats', ''));
Actually, Configs has a singleton approach.

2021-01-18 10:35 UTC, ildyria commented
@kamil4 please double check.

2021-01-18 12:11 UTC, cleytontiagosorinho approved these changes
Ajuda nessa questão

2021-01-18 15:19 UTC, kamil4 commented on app/Actions/Import/Exec.php
> +		// star als wildcard (as in *.jpg)
Oh, I know, I did actually learn Dutch during my 5+ years in NL. Near the end my English even acquired Dutch accent :smiley:.

2021-01-18 16:16 UTC, kamil4 approved these changes
OK, importing nested folders works now.

I should point out that I tested only the import via GUI; I have no experience with using the command line for that.

Also, there's still the bug that I reported last night on Gitter, in that thumbs are missing for `Unsorted` or `Public` smart albums for non-admin users.

2021-01-18 16:16 UTC, kamil4 commented on app/Actions/Photo/Rotate.php
> +			Logs::error(__METHOD__, __LINE__, 'SynLinked images cannot be rotated');
Sy**m**linked :smile:.

2021-01-18 17:11 UTC, merged

2021-01-18 17:11 UTC, kamil4 commented on app/SmartAlbums/BareSmartAlbum.php
> +						->whereIn('album_id', $this->albumIds)
The `whereNotNull` seems redundant here given the `whereIn` right after it?