update CLI Takedate
LycheeOrg/Lychee pull request #874
Opened 2021-01-16 01:10 UTC by evoludolab

* option --timestamp added to set create_at to timestamp of media file for media that lacks EXIF information
* use same formatting for 'sysdate' as for 'takedate'

For background see #870

2021-01-16 05:51 UTC, kamil4 approved these changes
This looks good. We should also provide this functionality during regular import, but that can be done in a separate PR.

2021-01-16 12:33 UTC, ildyria requested changes
Looks good.
Untested.

Please fix the two comments. :smiley:

2021-01-16 12:33 UTC, ildyria commented on app/Console/Commands/Takedate.php
> +			$i++;
This `$i++` is not consistent with what is actually being done and is off by +1.
Just place it before the `continue` and at the end of the loop.

2021-01-16 12:33 UTC, ildyria commented on app/Console/Commands/Takedate.php
> +			$filename = $url;
why is this needed? `$url` is not used anymore afterwards.

if you do not like `$url` then just rename all the previous `$url` before by `$filename`.

2021-01-16 18:40 UTC, ildyria approved these changes

2021-01-18 10:40 UTC, merged

2021-01-18 12:09 UTC, cleytontiagosorinho approved these changes
Só os que compensa no momento

2021-01-18 12:10 UTC, cleytontiagosorinho approved these changes
As melhores opicoes